conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500

from movies import views as movies_views


urlpatterns = [
    path('', movies_views.index, name='index'),
    path('godmin/', admin.site.urls),
    path('netflix/', movies_views.netflix_list, name='netflix_list'),
    path('netflix/<int:rank>/', movies_views.netflix_detail, name='netflix_detail'),
    path('movies/', include('movies.urls')),
]

handler404 = 'movies.views.page_not_found'
handler500 = 'movies.views.server_error'

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.country_list, name='country_list'),
    path('<str:country>/', views.country_boxoffice, name='country_boxoffice'),
    path('<str:country>/<int:rank>/', views.country_detail, name='country_detail'),
]

movies/models.py
from django.db import models
import csv


# Create your models here.
class Movie(models.Model):
    country = models.CharField(max_length=100)
    rank = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    year = models.CharField(max_length=100)
    rated = models.CharField(max_length=100)
    released = models.CharField(max_length=100)
    runtime = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    director = models.CharField(max_length=100)
    actors = models.CharField(max_length=100)
    plot = models.TextField()
    poster = models.TextField()
    imdbID = models.CharField(max_length=100)
    production = models.CharField(max_length=100)
    imdbScore = models.CharField(max_length=100)
    trailer = models.TextField()
    trailer_img = models.TextField()

    @classmethod
    def add(cls):
        with open('movies/fixtures/movies.csv', 'r') as f:
            fieldnames = ['country', 'rank', 'title', 'year', 'rated', 'released', 'runtime', 'genre', 'director',
                  'actors', 'plot', 'poster', 'imdbID', 'production', 'imdbScore', 'trailer', 'trailer_img']
            reader = csv.reader(f)
            next(reader)
            for row in reader:
                temp = {key: row[idx] for idx, key in enumerate(fieldnames)}
                Movie.objects.create(**temp)

    def __str__(self):
        return f'{self.country} {self.rank} {self.title}'


class TVSeries(models.Model):
    rank = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    netflix_url = models.TextField()
    year = models.CharField(max_length=100)
    rated = models.CharField(max_length=100)
    season = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    plot = models.TextField()
    actors = models.CharField(max_length=100)
    trailer = models.TextField()
    thumbnail = models.TextField()

    @classmethod
    def add(cls):
        with open('movies/fixtures/netflix.csv', 'r') as f:
            fieldnames = ['rank', 'title', 'netflix_url', 'year', 'rated', 'season', 'genre', 'plot', 'actors',
                        'trailer', 'thumbnail']
            reader = csv.reader(f)
            next(reader)
            for row in reader:
                temp = {key: row[idx] for idx, key in enumerate(fieldnames)}
                TVSeries.objects.create(**temp)

    def __str__(self):
        return self.title

movies/forms.py
from django import forms
from .models import Movie

import requests
import json

class MovieCreationForm(forms.ModelForm):
    title = forms.CharField(max_length = 100)
    year = forms.IntegerField()

    def clean(self):
        cleaned_data = super(MovieCreationForm, self).clean()
        title = cleaned_data['title']
        year = cleaned_data['year']
        api_url = f'http://www.omdbapi.com/?apikey=556ed6ed&t={title}&y={year}&plot=full'
        data = json.loads(requests.get(api_url).text)
        if data['Response'] == 'False':
            raise forms.ValidationError('영화가 없다!!!!!!!!!!')

        cleaned_data['imdbId'] = data['imdbID']
        cleaned_data['rated'] = data['Rated']
        cleaned_data['released'] = data['Released']
        cleaned_data['runtime'] = data['Runtime']
        cleaned_data['actors'] = data['Actors']
        cleaned_data['plot'] = data['Plot']
        cleaned_data['poster'] = data['Poster']
        cleaned_data['ratings'] = data['Ratings']
        cleaned_data['imdbRating'] = data['imdbRating']
        cleaned_data['production'] = data['Production']
        return cleaned_data

movies/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404

from .models import Movie, TVSeries
from .forms import MovieCreationForm

import requests
from bs4 import BeautifulSoup
import json

countries = {'us': ['us', 'United States', 'https://cdn.countryflags.com/thumbs/united-states-of-america/flag-800.png'],
             'uk': ['uk', 'United Kingdom', 'https://cdn.countryflags.com/thumbs/united-kingdom/flag-800.png'],
             'fr': ['fr', 'France', 'https://cdn.countryflags.com/thumbs/france/flag-800.png'],
             'au': ['au', 'Australia', 'https://cdn.countryflags.com/thumbs/australia/flag-800.png'],
             'br': ['br', 'Brazil', 'https://cdn.countryflags.com/thumbs/brazil/flag-800.png'],
             'mx': ['mx', 'Mexico', 'https://cdn.countryflags.com/thumbs/mexico/flag-800.png'],}

# Create your views here.
def index(request):
    return render(request, 'movies/index.html')


def country_list(request):
    context = {
        'countries': countries
    }
    return render(request, 'movies/country_list.html', context)


def country_boxoffice(request, country):
    movies = get_list_or_404(Movie, country=country)
    context = {
        'country': country,
        'flag': countries[country][2],
        'country_name': countries[country][1],
        'movies': movies,
    }
    return render(request, 'movies/country_boxoffice.html', context)

def country_detail(request, country, rank):
    movie = get_object_or_404(Movie, country=country, rank=rank)
    context = {
        'country': country,
        'country_name': countries[country][1],
        'movie': movie,
        'directors': movie.director.split(', '),
        'actors': movie.actors.split(', '),
        'genres': movie.genre.split(', '),
    }
    return render(request, 'movies/movie_detail.html', context)

def netflix_list(request):
    serieses = TVSeries.objects.all()
    context = {
        'serieses': serieses
    } 
    return render(request, 'movies/netflix_list.html', context)

def netflix_detail(request, rank):
    series = get_object_or_404(TVSeries, rank=rank)
    context = {
        'series': series,
        'actors': series.actors.split(',\xa0')
    }
    return render(request, 'movies/netflix_detail.html', context)
    
def page_not_found(request):
    return render(request, 'movies/404.html')
    
def server_error(request):
    return render(request, 'movies/404.html')

movies/templates/movies/country_boxoffice.html
{% extends 'base.html' %}

{% block body %}
<div class="container-fluid">
    <!-- nav -->
    {% include 'nav.html' %}
    <!-- end nav -->

    <!-- box-intro -->
    <section class="box-intro"
             style="background: -webkit-linear-gradient( rgba(255, 255, 255, 0.85), rgba(255, 255, 255, 0.85)), url({{flag}});
                    background: linear-gradient( rgba(255, 255, 255, 0.85), rgba(255, 255, 255, 0.85)), url({{flag}});
                    background-size: cover;
                    background-attachment: fixed;
                    background-position: center center;
                    text-align: center;">
        <div class="table-cell">
            <h1 class="box-headline letters rotate-2">
                <span class="box-words-wrapper">
                    <b class="is-visible">{{country_name}} </b>
                    <b>Box&nbsp;Office </b>
                    <b>Top&nbsp;10 </b>
                </span>
            </h1>
            <h5>It's Show Time!</h5>
        </div>

        <div class="mouse">
            <div class="scroll"></div>
        </div>
    </section>
    <!-- end box-intro -->
</div>

<!-- portfolio div -->
<div class="portfolio-div" style='background-color: #151313'>
    <div class="portfolio">
        <div class="no-padding portfolio_container">
            <!-- No.3 -->
            <div class="col-md-3 col-sm-6 fashion logo">
                <a href="{% url 'movies:country_detail' country=country rank=movies.2.rank %}" class="portfolio_item">
                    <img style='width: 100%;' src="{{movies.2.poster}}" alt="image" class="img-responsive" />
                    <div class="portfolio_item_hover">
                        <div class="portfolio-border clearfix">
                            <div class="item_info">
                                <span>{{movies.2.title}}</span>
                                <em>{{movies.2.released}}</em>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end No.3 -->

            <!-- No.4 -->
            <div class="col-md-3 col-sm-6 ads graphics">
                <a href="{% url 'movies:country_detail' country=country rank=movies.3.rank %}" class="portfolio_item">
                    <img style='width: 100%;' src="{{movies.3.poster}}" alt="image" class="img-responsive" />
                    <div class="portfolio_item_hover">
                        <div class="portfolio-border clearfix">
                            <div class="item_info">
                                <span>{{movies.3.title}}</span>
                                <em>{{movies.3.released}}</em>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end No.4 -->

            <!-- No.1 -->
            <div class="col-md-6 col-sm-12 photography" style="overflow: hidden">
                <a href="{% url 'movies:country_detail' country=country rank=movies.0.rank %}" class="portfolio_item">
                    <img style="width: 100%;" src="{{movies.0.poster}}" alt="image" class="img-responsive" />
                    <div class="portfolio_item_hover">
                        <div class="portfolio-border clearfix">
                            <div class="item_info">
                                <span>{{movies.0.title}}</span>
                                <em>{{movies.0.released}}</em>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end No.1 -->

            <!-- No.5 -->
            <div class="col-md-3 col-sm-6 fashion ads">
                <a href="{% url 'movies:country_detail' country=country rank=movies.4.rank %}" class="portfolio_item">
                    <img style='width: 100%;' src="{{movies.4.poster}}" alt="image" class="img-responsive" />
                    <div class="portfolio_item_hover">
                        <div class="portfolio-border clearfix">
                            <div class="item_info">
                                <span>{{movies.4.title}}</span>
                                <em>{{movies.4.released}}</em>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end No.5 -->

            <!-- No.6 -->
            <div class="col-md-3 col-sm-6 graphics ads">
                <a href="{% url 'movies:country_detail' country=country rank=movies.5.rank %}" class="portfolio_item">
                    <img style='width: 100%;' src="{{movies.5.poster}}" alt="image" class="img-responsive" />
                    <div class="portfolio_item_hover">
                        <div class="portfolio-border clearfix">
                            <div class="item_info">
                                <span>{{movies.5.title}}</span>
                                <em>{{movies.5.released}}</em>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end No.6 -->

            <!-- No.2 -->
            <div class="col-md-6 col-sm-12 photography">
                <a href="{% url 'movies:country_detail' country=country rank=movies.1.rank %}" class="portfolio_item">
                    <img style='width: 100%;' src="{{movies.1.poster}}" alt="image" class="img-responsive" />
                    <div class="portfolio_item_hover">
                        <div class="portfolio-border clearfix">
                            <div class="item_info">
                                <span>{{movies.1.title}}</span>
                                <em>{{movies.1.released}}</em>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end No.2 -->

            <!-- No.7 -->
            <div class="col-md-3 col-sm-6 graphics ads">
                <a href="{% url 'movies:country_detail' country=country rank=movies.6.rank %}" class="portfolio_item">
                    <img style='width: 100%;' src="{{movies.6.poster}}" alt="image" class="img-responsive" />
                    <div class="portfolio_item_hover">
                        <div class="portfolio-border clearfix">
                            <div class="item_info">
                                <span>{{movies.6.title}}</span>
                                <em>{{movies.6.released}}</em>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end No.7 -->

            <!-- No.8 -->
            <div class="col-md-3 col-sm-6 graphics ads">
                <a href="{% url 'movies:country_detail' country=country rank=movies.7.rank %}" class="portfolio_item">
                    <img style='width: 100%;' src="{{movies.7.poster}}" alt="image" class="img-responsive" />
                    <div class="portfolio_item_hover">
                        <div class="portfolio-border clearfix">
                            <div class="item_info">
                                <span>{{movies.7.title}}</span>
                                <em>{{movies.7.released}}</em>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end No.8 -->

            <!-- No.9 -->
            <div class="col-md-3 col-sm-6 graphics ads">
                <a href="{% url 'movies:country_detail' country=country rank=movies.8.rank %}" class="portfolio_item">
                    <img style='width: 100%;' src="{{movies.8.poster}}" alt="image" class="img-responsive" />
                    <div class="portfolio_item_hover">
                        <div class="portfolio-border clearfix">
                            <div class="item_info">
                                <span>{{movies.8.title}}</span>
                                <em>{{movies.8.released}}</em>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end No.9 -->

            <!-- No.10 -->
            <div class="col-md-3 col-sm-6 graphics ads">
                <a href="{% url 'movies:country_detail' country=country rank=movies.9.rank %}" class="portfolio_item">
                    <img style='width: 100%;' src="{{movies.9.poster}}" alt="image" class="img-responsive" />
                    <div class="portfolio_item_hover">
                        <div class="portfolio-border clearfix">
                            <div class="item_info">
                                <span>{{movies.9.title}}</span>
                                <em>{{movies.9.released}}</em>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end No.10 -->
        </div>
        <!-- end portfolio_container -->
    </div>
    <!-- portfolio -->
</div>
<!-- end portfolio div -->

{% endblock %}

movies/templates/movies/country_list.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
    {% include 'nav.html' %}
</div>

<!-- top-bar -->
<div class="top-bar">
    <h1>Select Any Country</h1>
</div>
<!-- end top-bar -->

<!-- portfolio div -->
<div class="container">
  <div class="portfolio-div">
      <div class="portfolio">
          <div class="no-padding portfolio_container">
              <!-- United States -->
              <div class="col-md-4 col-sm-6 white-border fashion logo">
                  <a href="{% url 'movies:country_boxoffice' countries.us.0 %}" class="portfolio_item">
                      <img width=100% src="http://cdn.countryflags.com/thumbs/united-states-of-america/flag-square-500.png" alt="image" class="img-responsive" />
                      <div class="portfolio_item_hover">
                          <div class="portfolio-border clearfix">
                              <div class="item_info">
                                  <span>United States</span>
                                  <!-- <em>{{movies.2.released}}</em> -->
                              </div>
                          </div>
                      </div>
                  </a>
              </div>
              <!-- end United States -->

              <!-- United Kingdom -->
              <div class="col-md-4 col-sm-6 white-border fashion logo">
                  <a href="{% url 'movies:country_boxoffice' countries.uk.0 %}" class="portfolio_item">
                      <img width=100% src="https://cdn.countryflags.com/thumbs/united-kingdom/flag-square-500.png" alt="image" class="img-responsive" />
                      <div class="portfolio_item_hover">
                          <div class="portfolio-border clearfix">
                              <div class="item_info">
                                  <span>United Kingdom</span>
                                  <!-- <em>{{movies.2.released}}</em> -->
                              </div>
                          </div>
                      </div>
                  </a>
              </div>
              <!-- end United Kingdom -->

              <!-- France -->
              <div class="col-md-4 col-sm-6 white-border fashion logo">
                  <a href="{% url 'movies:country_boxoffice' countries.fr.0 %}" class="portfolio_item">
                      <img width=100% src="https://cdn.countryflags.com/thumbs/france/flag-square-500.png" alt="image" class="img-responsive" />
                      <div class="portfolio_item_hover">
                          <div class="portfolio-border clearfix">
                              <div class="item_info">
                                  <span>France</span>
                                  <!-- <em>{{movies.2.released}}</em> -->
                              </div>
                          </div>
                      </div>
                  </a>
              </div>
              <!-- end France -->

              <!-- Australia -->
              <div class="col-md-4 col-sm-6 white-border fashion logo">
                  <a href="{% url 'movies:country_boxoffice' countries.au.0 %}" class="portfolio_item">
                      <img width=100% src="https://cdn.countryflags.com/thumbs/australia/flag-square-500.png" alt="image" class="img-responsive" />
                      <div class="portfolio_item_hover">
                          <div class="portfolio-border clearfix">
                              <div class="item_info">
                                  <span>Australia</span>
                                  <!-- <em>{{movies.2.released}}</em> -->
                              </div>
                          </div>
                      </div>
                  </a>
              </div>
              <!-- end Australia -->

              <!-- Brazil -->
              <div class="col-md-4 col-sm-6 white-border fashion logo">
                  <a href="{% url 'movies:country_boxoffice' countries.br.0 %}" class="portfolio_item">
                      <img width=100% src="https://cdn.countryflags.com/thumbs/brazil/flag-square-500.png" alt="image" class="img-responsive" />
                      <div class="portfolio_item_hover">
                          <div class="portfolio-border clearfix">
                              <div class="item_info">
                                  <span>Brazil</span>
                                  <!-- <em></em> -->
                              </div>
                          </div>
                      </div>
                  </a>
              </div>
              <!-- end Brazil -->

              <!-- Mexico -->
              <div class="col-md-4 col-sm-6 white-border fashion logo">
                  <a href="{% url 'movies:country_boxoffice' countries.mx.0 %}" class="portfolio_item">
                      <img width=100% src="https://cdn.countryflags.com/thumbs/mexico/flag-square-500.png" alt="image" class="img-responsive" />
                      <div class="portfolio_item_hover">
                          <div class="portfolio-border clearfix">
                              <div class="item_info">
                                <span>Mexico</span>
                                <!-- <em></em> -->
                              </div>
                          </div>
                      </div>
                  </a>
              </div>
              <!-- end Mexico -->

              <!-- Scheduled -->
              <div class="col-md-4 col-sm-6 white-border fashion logo">
                  <a href="" class="portfolio_item">
                      <img src="https://i.pinimg.com/originals/b1/30/bc/b130bcaf14e3033762c8232b89549b1d.jpg" alt="image" class="img-responsive" />
                      <div class="portfolio_item_hover">
                          <div class="portfolio-border clearfix">
                              <div class="item_info">
                                <span>Coming Soon</span>
                                <em></em>
                              </div>
                          </div>
                      </div>
                  </a>
              </div>
              <!-- end Scheduled -->
          </div>
          <!-- end portfolio_container -->
      </div>
      <!-- portfolio -->
  </div>
  <!-- end portfolio div -->
</div>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block body %}
<div class="container-fluid">
    <!-- nav -->
    {% include 'nav.html' %}
    <!-- end nav -->

    <!-- box-intro -->
    <section class="box-intro">
        <div class="table-cell" style='padding-top: 20%; vertical-align: baseline;'>
            <h1 class="box-headline letters rotate-2" style='font-size: 100px;'>
                <span class="box-words-wrapper text-center">
                    <b class="is-visible">Best&nbsp;Movies</b>
                    <b>&nbsp; and </b>
                    <b>Chill&nbsp;Netflix</b>
                </span>
            </h1>
            <h5>What's next?</h5>
        </div>

        <div class="mouse">
            <div class="scroll"></div>
        </div>
    </section>
    <!-- end box-intro -->
</div>

<!-- portfolio div -->
<div class="portfolio-div">
    <div class="portfolio">
        <div class="no-padding portfolio_container">
          <!-- Movies -->
          <div class="col-md-6 col-sm-12 photography">
              <a href="{% url 'movies:country_list' %}" class="portfolio_item">
                  <img style="width: 100%;" src="https://trello-attachments.s3.amazonaws.com/5cdd02c788550b2dcd8b7cc0/773x773/9a94cf288269e351fc94115b5005f7ec/21stcenturyfox.png" alt="image" class="img-responsive" />
                  <div class="portfolio_item_hover">
                      <div class="portfolio-border clearfix">
                          <div class="item_info">
                              <span>Country's Box Office</span>
                              <em>18th week 2019</em>
                          </div>
                      </div>
                  </div>
              </a>
          </div>
          <!-- end Movies -->
          <!-- Netflix -->
          <div class="col-md-6 col-sm-12 photography" style="overflow: hidden">
              <a href="{% url 'netflix_list' %}" class="portfolio_item">
                  <img style="width: 100%;" src="https://upload.wikimedia.org/wikipedia/commons/f/ff/Netflix-new-icon.png" alt="image" class="img-responsive" />
                  <div class="portfolio_item_hover">
                      <div class="portfolio-border clearfix">
                          <div class="item_info">
                              <span>Netflix and Chill</span>
                              <em>May 2019</em>
                          </div>
                      </div>
                  </div>
              </a>
          </div>
          <!-- end Netflix -->
        </div>
        <!-- end portfolio_container -->
    </div>
    <!-- portfolio -->
</div>
<!-- end portfolio div -->
{% endblock%}

movies/templates/movies/movie_detail.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <div class="container-fluid">
        {% include 'nav.html' %}
    </div>
    
    <!-- top-bar -->
    <div class="top-bar">
        <h1>{{movie.title}}</h1>
        <p><a href="{% url 'index' %}">Home</a> / <a href="{% url 'movies:country_list' %}">Movies</a> / <a href="{% url 'movies:country_boxoffice' country=country %}">{{country_name}}</a> / {{movie.title}}</p>
    </div>
    <!-- end top-bar -->
    
    <!-- main-container -->
    <div class="container main-container">
        <div class="col-md-12">
            <div class="embed-responsive embed-responsive-16by9"> 
                <iframe width="100" src="{{movie.trailer}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div> 
            <div class="h-30"></div>
        </div>

        <div class="col-md-12">
            <h3>{{movie.title}}</h3>
            <h5>{{movie.released}}</h5>
            <div class="h-30"></div>
        </div>

        <div class="col-md-12">
            <p class='plot'>{{movie.plot}}</p>
            <div class="h-30"></div>
        </div>

        <div class="row">
            <!-- Director-box -->
            <div class="col-md-4 service-box text-center">
                <i class="ion-android-options size-50"></i>
                <h3>Director</h3>
                <div class="h-10"></div>
                {% for director in directors %}
                    <p>{{director}}</p>
                {% endfor %}
            </div>
            <!-- end Director-box -->
            
            <!-- Actors-box -->
            <div class="col-md-4 service-box text-center">
                <i class="ion-android-favorite-outline size-50"></i>
                <h3>Actors</h3>
                <div class="h-10"></div>
                {% for actor in actors %}
                    <p>{{actor}}</p>
                {% endfor %}
            </div>
            <!-- end Actors-box -->

            <!-- Genre-box -->
            <div class="col-md-4  service-box text-center">
                <i class="ion-android-checkmark-circle size-50"></i>
                <h3>Genre</h3>
                <div class="h-10"></div>
                {% for genre in genres %}
                <p>{{genre}}</p>
                {% endfor %}
            </div>
            <!-- end Genre-box -->
        </div>

        <div class="row">
            <!-- Runtime-box -->
            <div class="col-md-4  service-box text-center">
                <i class="ion-ios-pulse-strong size-50"></i>
                <h3>Runtime</h3>
                <div class="h-10"></div>
                <p>{{movie.runtime}}</p>
            </div>
            <!-- end Runtime-box -->

            <!-- IMdbScore-box -->
            <div class="col-md-4  service-box text-center">
                <i class="ion-earth size-50"></i>
                <h3>IMDb Score</h3>
                <div class="h-10"></div>
                <p>{{movie.imdbScore}}</p>
            </div>
            <!-- end service-box -->

            <!-- Rated-box -->
            <div class="col-md-4  service-box text-center">
                <i class="ion-speedometer size-50"></i>
                <h3>Rated</h3>
                <div class="h-10"></div>
                <p>{{movie.rated}}</p>
            </div>
        <!-- end Rated-box -->
        </div>
    </div>
    <!-- end main-container -->

{% endblock %}

movies/templates/movies/netflix_list.html
{% extends 'base.html' %}

{% block body %}
<div class="container-fluid">
  {% include 'nav.html' %}
</div>

<!-- box-intro -->
<section class="box-intro">
    <div class="table-cell" style='padding-top: 20%; vertical-align: baseline;'>
        <h1 class="box-headline letters rotate-2" style='font-size: 100px;'>
            <span class="box-words-wrapper">
                <b class="is-visible">'I&nbsp;NEED&nbsp;TO&nbsp;STOP' </b>
                <b>I&nbsp;WHISPERED&nbsp;TO&nbsp;MYSELF, </b>
                <b>AS&nbsp;I&nbsp;CLICKED&nbsp;NEXT&nbsp;EPISODE. </b>
            </span>
        </h1>
    </div>

    <div class="mouse">
        <div class="scroll"></div>
    </div>
</section>
<!-- end box-intro -->

<!-- portfolio div -->
<div class="portfolio-div" style='background-color: #151313'>
    <div class="portfolio">
        <div class="no-padding portfolio_container">
            {% for series in serieses %}
            <!-- United States -->
            <div class="col-md-3 col-sm-4 col-xs-6 fashion logo">
                <a href="{% url 'netflix_detail' rank=series.rank %}" class="portfolio_item">
                    <img width=100% src="{{series.thumbnail}}" alt="image" class="img-responsive" />
                    <div class="portfolio_item_hover">
                        <div class="portfolio-border clearfix">
                            <div class="item_info">
                                <span>{{series.title}}</span>
                                <!-- <em>{{movies.2.released}}</em> -->
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end United States -->
            {% endfor %}
        </div>
        <!-- end portfolio_container -->
    </div>
    <!-- portfolio -->
</div>
<!-- end portfolio div -->
{% endblock %}

templates/nav.html
{% load static %}

<!-- box header -->
<header class="box-header">
    <div class="box-logo">
        <a href="{% url 'index' %}"><img src="{% static 'img/logo.png' %}" width="80" alt="Logo"></a>
    </div>
    <!-- box-nav -->
    <a class="box-primary-nav-trigger" href="#0">
        <span class="box-menu-text">Menu</span><span class="box-menu-icon"></span>
    </a>
    <!-- box-primary-nav-trigger -->
</header>
<!-- end box header -->

<!-- nav -->
<nav>
    <ul class="box-primary-nav">
        <li><a class='box-label' href="{% url 'index' %}">Home</a></li>
        <li class="box-label">Watches</li>
        
        <li><a href="{% url 'movies:country_list' %}">Movies</a></li>
        <li><a href="{% url 'netflix_list' %}">Netflix</a></li>
        
        <li class="box-label">Follow me</li>
        
        <li class="box-social"><a href="#0"><i class="ion-social-facebook"></i></a></li>
        <li class="box-social"><a href="#0"><i class="ion-social-instagram-outline"></i></a></li>
        <li class="box-social"><a href="#0"><i class="ion-social-twitter"></i></a></li>
        <li class="box-social"><a href="#0"><i class="ion-social-dribbble"></i></a></li>
    </ul>
</nav>
<!-- end nav -->